### ISSUE TITLE
Action Type is always 0

### ISSUE THREAD

**Issue by abhineetchandan** [X-SLAYER/flutter_accessibility_service#1]
@X-SLAYER  When using this plugin to receive accessibility events the action type that is received of an event, It is always 0. Why is it so?

**Comment by X-SLAYER** [comment]
it's refereed in the [documentation](https://developer.android.com/reference/android/view/accessibility/AccessibilityEvent#getAction()) that will get the performed action that triggered this event I don't know if is there any other ways to trigger the event so the number else if it is useless I will remove it in the next version release

**Comment by abhineetchandan** [comment]
okay. I will close this now
