### ISSUE TITLE
[Android 14] Required RECEIVER_NOT_EXPORTED/RECEIVER_EXPORTED

### ISSUE THREAD

**Issue by sarthakydv** [X-SLAYER/flutter_accessibility_service#13]
Required param for support on android 14.

Discussion: https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec

**Comment by sarthakydv** [comment]
I have add a fix in a private fork.
I can't make a branch here.
Here are the changes:
1. `android/build.gradle`
	`compileSdkVersion` 31 -> 34 (so that the latest APIs are available
2. `android/src/main/java/slayer/accessibility/service/flutter_accessibility_service/FlutterAccessibilityServicePlugin.java`
	add imports:
```
import android.annotation.SuppressLint;
import android.os.Build;
```

Annotate `onListen` with `@SuppressLint("WrongConstant")` - the lint is giving a false warning. I have reported it.

Replace `context.registerReceiver(accessibilityReceiver, intentFilter);` with
```
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
                context.registerReceiver(accessibilityReceiver, intentFilter, Context.RECEIVER_EXPORTED);
            }else{
                context.registerReceiver(accessibilityReceiver, intentFilter);
            }
```

**Comment by X-SLAYER** [comment]
I will try that otherwise try to make a pull request directly

**Comment by sarthakydv** [comment]
Please do it, we are only managing our private fork

**Comment by X-SLAYER** [comment]
a new version i published suppor android 14 + new core features [flutter_accessibility_service 0.2.3](https://pub.dev/packages/flutter_accessibility_service)

**Comment by bugrevealingbme** [comment]
not fixed
