### ISSUE TITLE
[Query] Fix for StackOverflow in `getSubNodes`

### ISSUE THREAD

**Issue by sarthakydv** [X-SLAYER/flutter_accessibility_service#16]
There have been recent changes in the package to make a fix for this issue.

Can you please explain how it is fixed?

If not fixed, I would love to discuss on how we can do it.

A team member has added a set to handle duplicates but It feels unreliable because of `generateNodeId`
(E.g. In a chat application, parent node can be the same user name for multiple entries)

PR for changes by @avisihag #15

**Comment by sarthakydv** [comment]
@avisihag has removed dependence on `generateNodeId`

Please take a look

**Comment by X-SLAYER** [comment]
Sure I'll check it and merge thanks

**Comment by sarthakydv** [comment]
@X-SLAYER your recent changes did not address this issue?

**Comment by X-SLAYER** [comment]
i didn't come to a case that stuck in a loop of subnodes

**Comment by sarthakydv** [comment]
@X-SLAYER The fix is working well, can you please merge and make a release?

**Comment by avisihag** [comment]
>  i didn't come to a case that stuck in a loop of subnodes

Our app is getting repeated instances of `Fatal Exception: java.lang.StackOverflowError: stack size 8188KB` in the getNextTexts method which is moved to the getSubNodes method in the latest release.

Please have a look at the PR I've raised to fix this particular issue.

**Comment by X-SLAYER** [comment]
PL request merged wait till i post a new version of the app
