### ISSUE TITLE
There are some questions before use

### ISSUE THREAD

**Issue by endachao** [X-SLAYER/flutter_accessibility_service#2]
hi

I was looking for information about flutter accessibility service and found this project, it's really an interesting project

However, I am not an android developer, can this project help me to control other APPs?

For example, can I use this project to control android to automatically click on an application? Do something automatically after opening the app?

Looking forward to your help, thank you

**Comment by X-SLAYER** [comment]
Hello, currently the plugin does not give access to make clicks or control some inputs ext... 
The plugin just gives you the information about the status of the current appd like isActive their text

**Comment by aknaspk** [comment]
Hi,
Any updates ??

**Comment by zhangyusheng211** [comment]
Hello, is there any plan to support this function in the future? I hope to realize software automation control function with the help of this plugin.
