### ISSUE TITLE
Have to request permission on each run

### ISSUE THREAD

**Issue by tanzil114** [X-SLAYER/flutter_accessibility_service#21]
Whenever we are using any feature from the plugin such as showOverlayWindow, performGlobalAction, etc. we have to request permission again, on each run.

Expected Output: We should be able to request the permission once, and it should not be required for future runs, unless user manually revokes the permission, or the app gets deleted.

Also, if this gets implemented, it would be great to have revokeAccessibilityPermission as well.

By the way, huge thanks for building this, as this takes care of all the heavy lifting we'll have to do to implement Accessability service in Flutter.

**Comment by X-SLAYER** [comment]
hello did you try it on release mode cuz I think this related to only debugging

**Comment by tanzil114** [comment]
Yes, after some digging I found out that as well. Accessability service gets stopped when we stop debugging, as it basically force stops the debugged app.
