### ISSUE TITLE
update Namespace

### ISSUE THREAD

**Issue by haygcao** [X-SLAYER/flutter_accessibility_service#34]
can  you update namespace to build grade

**Comment by arpit24sahu** [comment]
Step 1 - Fork the Repo
Step 2 - Create a new PR
Step 3 - Make the change in the file `android/build.gradle`

```
.
.
.
android {
    compileSdkVersion 34

    namespace 'slayer.accessibility.service.flutter_accessibility_service'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
.
.
```
    
 Step 4 - Push the change.
 Step 5 - Use your branch in your pubspec.yaml
 
 Hope it helps :-)
