### ISSUE TITLE
Stream stops when app is closed

### ISSUE THREAD

**Issue by tolotrasamuel** [X-SLAYER/flutter_accessibility_service#5]
Hello,

Thank you for this. Is it normal that the stream stops when the app is closed ? I have used Accessibility Service on Android app before and even if the app is closed, the streams continue.  Is there any way to achieve the same with this plugin ? Like using an isolate or something like that?

Thanks

**Comment by X-SLAYER** [comment]
yes you can by using foreground task 
you can check this [example](https://github.com/X-SLAYER/foreground_app_test) you just need to replace the service if foreground with the accessibility service
