### ISSUE TITLE
Invalid Manifest

### ISSUE THREAD

**Issue by CrazyJannis44** [X-SLAYER/flutter_accessibility_service#7]
![grafik](https://user-images.githubusercontent.com/36644360/219907052-eccb1f02-91e6-4fcb-a728-f07ec696bee5.png)
![grafik](https://user-images.githubusercontent.com/36644360/219907113-e765217d-8f34-49ff-a891-cc4108bc471a.png)
![grafik](https://user-images.githubusercontent.com/36644360/219907067-43c9fbca-cc3d-4d43-a287-02760934b148.png)

**Comment by X-SLAYER** [comment]
i think probel mrelated to your project creation from the beginning try to run the example folder and test if it works
