### ISSUE TITLE
I have some questions.

### ISSUE THREAD

**Issue by zhangyusheng211** [X-SLAYER/flutter_accessibility_service#9]
Hello, is there any plan to support this function in the future? I hope to realize software automation control function with the help of this plugin.

_Originally posted by @zhangyusheng211 in https://github.com/X-SLAYER/flutter_accessibility_service/issues/2#issuecomment-1517893370_

**Comment by X-SLAYER** [comment]
[2#issuecomment-1209044622](https://github.com/X-SLAYER/flutter_accessibility_service/issues/2#issuecomment-1209044622)
